version: "3"

services:
  base-api:
    env_file:
      - app.env
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        DBUSER: ${DBUSER}
        DBPASS: ${DBPASS}
        DBNAME: ${DBNAME}
    volumes:
      - ../..:/app/workspace
    command: /bin/sh "/app/workspace/.dev/init.sh"
    ports:
      - "127.0.0.1:${PORT}:3000"

